trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: SRM
  
steps:
- task: BlackDuckSecurityScan@2.0.0
  displayName: 'Software Risk Manager'
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))
  inputs:
     SRM_URL: $(SRM_URL)
     SRM_APIKEY: $(SRM_APIKEY)
     SRM_ASSESSMENT_TYPES: "SCA,SAST"
###     SRM_PROJECT_NAME: $(Build.Repository.Name)


### Uncomment below configuration to add custom logic based on return status    
# - task: CmdLine@2
#   displayName: 'Command Line'
#   condition: not(eq(variables['BlackDuckSecurityScan.status'], '0'))
#   inputs:
#     script: |
#       echo Black Duck Security Scan exit status - $(BlackDuckSecurityScan.status)